name: 'sync-to-other-hub'

on:
  push:
  delete:

jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./
        with:
          target_repository: 'git@gitee.com:ttionya/sync-test.git'
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
