name: 'test'

on:
  push:
  delete:

jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # ref
          fetch-depth: 0
      - uses: ./
        with:
          target_repository: 'git@github.com:ttionya/test-action-sync-test.git'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
